# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0003_auto_20161229_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osbb.HousingCooperative'),
        ),
    ]
