# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0004_auto_20161229_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='housing_cooperative',
            new_name='cooperative',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
