# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:47
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0005_auto_20161230_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingcooperativeservice',
            old_name='housing_cooperative',
            new_name='cooperative',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
