# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0006_auto_20170103_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmeter',
            name='meter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osbb.Meter'),
        ),
    ]
