# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0008_auto_20170103_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='receipt_text',
        ),
    ]
