# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0009_auto_20170103_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
