# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0009_auto_20170103_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
