# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0010_auto_20170103_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
