# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0011_auto_20170103_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='tariff',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='tariff',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
