# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0012_auto_20170103_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='indicator_beginning',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='indicator_end',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='personal_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osbb.PersonalAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='tariff',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
