# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0013_auto_20170103_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='value',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
