# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0014_auto_20170103_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osbb.Apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='owner',
        ),
        migrations.AlterField(
            model_name='charge',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osbb.HousingCooperative'),
        ),
        migrations.DeleteModel(
            name='PersonalAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
