# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0017_auto_20170110_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('M2', 'Square meters'), ('MK', 'Square meters per kilocalorie'), ('KW', 'Kilowatt'), ('CM', 'Cubic meter')], max_length=2),
        ),
    ]
