# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:15
from __future__ import unicode_literals

from django.db import migrations
from osbb.models import UNITS


def create_optional_services(apps, schema_editor):
    Service = apps.get_model('osbb', 'Service')
    service = Service(name='Опалення', unit=UNITS[1][0])
    service.save()
    service = Service(name='Електроенергія', unit=UNITS[2][0])
    service.save()
    service = Service(
        name='Водопостачання та водовідведення', unit=UNITS[3][0])
    service.save()
    service = Service(name='Підігрів води', unit=UNITS[3][0])
    service.save()
    service = Service(name='Газ', unit=UNITS[3][0])
    service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0019_auto_20170110_1639'),
    ]

    operations = [
        migrations.RunPython(create_optional_services),
    ]
