# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0020_auto_20170110_1715'),
    ]

    operations = [
    ]
