# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0021_auto_20170111_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingcooperativeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
        ),
    ]
