# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0022_auto_20170111_0039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housingcooperativeservice',
            unique_together=set([('cooperative', 'service')]),
        ),
    ]
