# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0023_auto_20170111_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartments_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
