# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0024_house_apartments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='apartments_count',
            field=models.IntegerField(null=True),
        ),
    ]
