# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0025_auto_20170113_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='osbb.HousingCooperative'),
        ),
    ]
