# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0027_auto_20170113_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.AddField(
            model_name='house',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
