# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0029_auto_20170116_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='meter',
            new_name='requires_meter',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='unit',
        ),
        migrations.AddField(
            model_name='meter',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
            preserve_default=False,
        ),
    ]
