# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0030_auto_20170116_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmeter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='osbb.Apartment'),
        ),
    ]
