# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0031_auto_20170116_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentMeterIndicator',
            new_name='MeterIndicator',
        ),
        migrations.RemoveField(
            model_name='apartmentmeter',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='apartmentmeter',
            name='meter',
        ),
        migrations.AddField(
            model_name='meter',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='osbb.Apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meterindicator',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Meter'),
        ),
        migrations.DeleteModel(
            name='ApartmentMeter',
        ),
    ]
