# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0032_auto_20170116_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterindicator',
            name='period',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingcooperativeservice',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='osbb.HousingCooperative'),
        ),
    ]
