# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0033_auto_20170120_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterindicator',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='osbb.Meter'),
        ),
    ]
