# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0035_remove_meterindicator_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterindicator',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
