# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0036_auto_20170120_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterindicator',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
