# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0037_meterindicator_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='personal_account',
            new_name='account',
        ),
    ]
