# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0042_auto_20170125_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('M2', 'Square meters'), ('MK', 'Square meters per kilocalorie'), ('KW', 'Kilowatt'), ('CM', 'Cubic meter')], max_length=2)),
                ('tariff', models.IntegerField()),
                ('indicator_beginning', models.CharField(max_length=10)),
                ('indicator_end', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='osbb.Charge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
