# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0043_servicecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
