# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0044_auto_20170126_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='tariff',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
