# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0046_auto_20170126_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicecharge',
            name='unit',
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
            preserve_default=False,
        ),
    ]
