# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0047_auto_20170126_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModelTest',
        ),
    ]
