# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0050_remove_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
