# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0051_auto_20170206_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
