# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0052_auto_20170206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='dwelling_space',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating_area',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
