# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0054_auto_20170207_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
