# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0057_auto_20170213_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(max_length=100)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.HousingCooperative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
