# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0058_bankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='info',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='mfo',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
