# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0064_remove_house_apartments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='entrance',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
