# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 00:44
from __future__ import unicode_literals

from django.db import migrations


def fix_requires_meter(apps, schema_editor):
    Service = apps.get_model('osbb', 'Service')
    services = Service.objects.filter(required=False)
    for service in services:
        service.requires_meter = True
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0065_auto_20170220_2320'),
    ]

    operations = [
        migrations.RunPython(fix_requires_meter),
    ]
