# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0066_auto_20170225_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='period',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='value',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='comment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
