# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0068_auto_20170225_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osbb.Service'),
        ),
    ]
