# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0069_accountbalance_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osbb.Charge'),
        ),
    ]
