# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0073_accountbalance_rollback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmenttariff',
            name='date',
        ),
        migrations.RemoveField(
            model_name='apartmenttariff',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='apartmenttariff',
            name='value',
        ),
        migrations.RemoveField(
            model_name='housetariff',
            name='date',
        ),
        migrations.RemoveField(
            model_name='housetariff',
            name='value',
        ),
        migrations.AddField(
            model_name='apartmenttariff',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='housetariff',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartmenttariff',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
        ),
        migrations.AlterField(
            model_name='housetariff',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
        ),
    ]
