# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0074_auto_20170301_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttariff',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='osbb.Apartment'),
        ),
        migrations.AlterField(
            model_name='housetariff',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='osbb.House'),
        ),
    ]
