# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0075_auto_20170301_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
        ),
        migrations.AlterField(
            model_name='housetariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Service'),
        ),
    ]
