# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0076_auto_20170302_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tariff',
        ),
    ]
