# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 21:33
from __future__ import unicode_literals

from address.models import DEFAULT_CITY_NAME
from django.db import migrations


def create_default_city(apps, schema_editor):
    City = apps.get_model('address', 'City')
    city = City(name=DEFAULT_CITY_NAME)
    city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_city),
    ]
